timeout: 5
verbose: yes
serial: yes

randomise_memory: no

interface_resolution: 1280x720
interface_branding: HorizonOS
interface_branding_color: 4

/LunarisOS
    protocol: limine
    kernel_path: boot():/boot/kernel
    resolution: 1280x720x32